name       : desktopfolders
version    : 1.0.10
release    : 1
source     :
    - https://github.com/spheras/desktopfolder/archive/v1.0.10.tar.gz : 3cecc212882f6a8b03f03adb5582d4fb69f0433478f6175072a50a387bfd3d44
license    : GPL-3.0-or-later
component  : desktop
summary    : Organize your desktop with panels that hold your things
description: |
    Organize your desktop with panels that hold your things.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libwnck-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
