name       : desktopfolders
version    : 1.1.2
release    : 4
source     :
    - https://github.com/spheras/desktopfolder/releases/download/v1.1.2/desktopfolder-1.1.2.tar.gz : 26accc60b96036d505a2ef4255a4f108b8174c4b156f1bc6a1c77ede2b53a9fb
license    : GPL-3.0-or-later
component  : desktop
summary    : Organize your desktop with panels that hold your things
description: |
    Organize your desktop with panels that hold your things.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libwnck-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Do not autostart by default since it will actively conflict with Budgie's own Desktop Icons implementation
    rm -rf $installdir/etc
