name       : desktopfolders
version    : 1.1.3
release    : 5
source     :
    - https://github.com/spheras/desktopfolder/releases/download/v1.1.3/desktopfolder-1.1.3.tar.gz : b1ec22d93face7999b5a758bc1e03b402ac73d17da03ac6affc7d58aa2f971c5
license    : GPL-3.0-or-later
component  : desktop
summary    : Organize your desktop with panels that hold your things
description: |
    Organize your desktop with panels that hold your things.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libwnck-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Do not autostart by default since it will actively conflict with Budgie's own Desktop Icons implementation
    rm -rf $installdir/etc
