name       : desktopfolders
version    : 1.1.1
release    : 2
source     :
    - https://github.com/spheras/desktopfolder/archive/v1.1.1.tar.gz : c4b3a0d2e4d7119faf05513a504cd2e6b4817e936f9552348a66e0ed8799f546
license    : GPL-3.0-or-later
component  : desktop
summary    : Organize your desktop with panels that hold your things
description: |
    Organize your desktop with panels that hold your things.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libwnck-3.0)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-compilation-issues-with-vala-0.44.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
